# Welcome to Serverless!


service: stock-service

provider:
  name: aws
  runtime: python3.6
  stage: dev

functions:
  hello:
    handler: functions/handler.stock
    events:
      - http:
          path: stock
          method: get

package:
  exclude:
    - venv/**
    - __pycache__/**